# Generated by Django 6.1 on 2026-08-08 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feastoApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                (
                    "picture",
                    models.URLField(
                        default="https://placehold.co/600x400?text=No+Image"
                    ),
                ),
                ("cuisine", models.CharField(max_length=200)),
                ("rating", models.FloatField()),
            ],
        ),
    ]
