# Generated by Django 6.1 on 2026-08-08 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feastoApp", "0003_items"),
    ]

    operations = [
        migrations.RenameField(
            model_name="items",
            old_name="print",
            new_name="price",
        ),
        migrations.AlterField(
            model_name="items",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="feastoApp.restaurant",
            ),
        ),
    ]
