# Generated by Django 6.1 on 2026-08-09 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feastoApp", "0004_rename_print_items_price_alter_items_restaurant"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart",
                        to="feastoApp.customer",
                    ),
                ),
                (
                    "items",
                    models.ManyToManyField(related_name="carts", to="feastoApp.items"),
                ),
            ],
        ),
    ]
