# Generated by Django 6.1 on 2026-08-16 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feastoApp", "0005_cart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="address",
            field=models.CharField(max_length=200),
        ),
    ]
