# Generated by Django 6.1 on 2026-08-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feastoApp", "0006_alter_customer_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="items",
            name="picture",
            field=models.TextField(
                default="https://placehold.co/600x400?text=No+Image"
            ),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="picture",
            field=models.TextField(
                default="https://placehold.co/600x400?text=No+Image"
            ),
        ),
    ]
